listening-port=3478
tls-listening-port=5349
fingerprint
lt-cred-mech
realm=${TURN_REALM}
user=${TURN_USERNAME}:${TURN_PASSWORD}
external-ip=${TURN_EXTERNAL_IP}
min-port=${TURN_MIN_PORT}
max-port=${TURN_MAX_PORT}
cert=${TURN_TLS_CERT}
pkey=${TURN_TLS_KEY}
no-cli
no-loopback-peers
no-multicast-peers
stale-nonce=600
verbose
